# Parameters used to generate this project with aem-project-archetype

groupId=com.demosandbox
artifactId=aem-demosandbox-project
version=0.0.1-SNAPSHOT
package=com.demosandbox
appId=demosandbox
appTitle=demosandbox
aemVersion=cloud
sdkVersion=latest
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=general
singleCountry=y
includeDispatcherConfig=y
includeCif=n
includeForms=n
includeFormsenrollment=y
includeFormscommunications=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=n
enableSSR=n
precompiledScripts=n
includeFormsheadless=n
uiTestingFramework=cypress
